$(() => {

  //missedBalloons will contain the number of balloons within the top row
  let missedBalloons = 0;
  let $mediumBallons = $('.medium-area');
  let $fastBallons = $('.fast-area');
  const pop = $('li');

  //An if..else statment will check whether the top row contains three ballons. So long as it doesn't balloons will be generated by putting their ID into a random start area's square (picked by math.random).
  function generateBalloons() {
    let slowBallons = $('.slow-area')[Math.floor(Math.random()*$('.slow-area').length)];
    console.log(slowBallons);
    if (missedBalloons < 3) {
      slowBallons.setAttribute('id', 'slow');
    }
  }
  generateBalloons();

  //A mouseover event will take the balloon's ID away, therefore making it pop
  pop.mouseover(function() {
    $(this).removeAttr('id');
  });

  //An animation wil make the balloons travel up the screen

  //A for loop will check the top to see if any balloons have been missed. If there are not any it will keep running generateBalloons

  //A timer for 30 seconds will end the game




});
