$(() => {

  //missedBalloons will contain the number of balloons within the top row
  let missedBalloons = 0;
  //startArea is an array of the section of the board where the balloons will generate
  let $slowBallons = $('.slow-area');
  let $mediumBallons = $('.medium-area');
  let $fastBallons = $('.fast-area');

  //An if..else statment will check whether the top row contains three ballons. So long as it doesn't balloons will be generated by putting their ID into the start area's square
  function generateBalloons() {
    if (missedBalloons < 3) {
      $slowBallons.attr('id', 'slow');
    } else if (missedBalloons < 2) {
      $mediumBallons.attr('id', 'medium-area');
    } else
    $fastBallons.attr('id', 'fast-area');
  }
  generateBalloons();

  //A mouseover event will take the balloon's ID away, therefore making it pop
  $('.slow-area').mouseover(function() {
    $slowBallons.removeAttr('id');
  });
});
